<?php
$categories = $this->getCategoryCollection();
$categoryHelper = $this->getCategoryHelper();
$canshowImg = $this->canShowImage();
$title = $block->getTitle() ? __($block->getTitle()) : 'Categories';
?>
<?php if ($title):?>
<div class="block-title">
	<strong><?php /* @escapeNotVerified */ echo $title; ?></strong>
</div>
<?php endif ?>
<div class="block-content catalog-category">
<?php
//echo get_class($categories);
foreach($categories as $category):
        var_dump(get_class_methods($category));
        $cat = $this->getCategorymodel($category->getId());
        // var_dump($cat->getImageUrl());
        var_dump($cat);
        // var_dump($cat->debug());die;
        ?>
        <span class="category">
        	<a href="<?php echo $cat->getUrl(); ?>">
        		<?php if($canshowImg && $cat->getImageUrl()):?>
        			<img src="<?= $cat->getImageUrl(); ?>" alt="" width="<?=$this->getImagewidth();?>" height="<?=$this->getImageheight()?>"/>
        		<?php else:?>
        		<span class="cat-title"><?php echo $cat->getName(); ?></span>
        		<?php endif;?>
        	</a>
        		<?php if($canshowDescription):?>
        		        <span class="cat-description"><?php echo $cat->getDescription(); ?></span>
        		<?php endif;?>
        </span>
        <?php
endforeach;
?>
</div